# Generated by Django 6.0.6 on 2026-06-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
